name: Python CI



on:

  workflow_dispatch: #déclenchement manuelle

  push:

    branches:

      - main



jobs: #création d'un jobs

  tests: #nom du premier jobs

    runs-on: ubuntu-latest #machine sur laquelle cela va tourner

    steps:

      - uses: actions/checkout@v3 #On va pull le depôt git

      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install requirements
        run: |
          python -m pip install -r requirements.txt

      - name: Python pytest
        run: |
          python -m pytest
      - name: Python pylint
        run: |
          pylint application/ tests/  --fail-under=20
         



